[theme]
primaryColor = "#E91E63"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FCE4EC"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false
